### ISSUE TITLE
Including a `'` in free text search throws error

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#1006]
The search functionality throws an error if we include `'` in the free text search.

This is a character that can legitimately occur in names and addresses, so it should be allowable.

**Comment by IanMayo** [comment]
It currently looks like this is an up-stream dependency on `soul-cli`.

_Maybe_ we could have this workaround:
- introduce `sanitise` and `un-sanitise` methods in our DataProvider. These will process URLs before they are sent to soul, and process data received back from soul.
- the methods will exchange `'` for `&quot;` before sending to soul, and the reverse on return

**Comment by IanMayo** [comment]
Hello @TahaKhanAbdalli - we have learned the underlying reason for this (SQLite dialect of SQL) - https://github.com/thevahidal/soul/issues/146

Could you have a think about how we would handle this issue in VAL, rather than waiting for a `Soul` fix? We would need to convert the strings on the way to Soul, as well as the returned content.

**Comment by TahaKhanAbdalli** [comment]
I have checked in frontend if we use `''` instead of `'` it is getting the correct data, and I don't think so we need to implement any `sanitise` and `un-sanitise` method in our DataProvider.

**Comment by IanMayo** [comment]
Sure, but I can't get users to enter O''Brien instead of O'Brien.

**Comment by TahaKhanAbdalli** [comment]
Oky, Let me create the function which convert the single quote into double quote.
