### ISSUE TITLE
Offer cosmetic clues of working on test server

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#1026]
The software-testing guy reported a `Fail` because it wasn't easy to tell if he was on a test server or a publication server.

Since VAL is unaware of the infrastructure it is installed upon I couldn't really think of a way of resolving this, and once testing was complete the issue would go away anyway.

But, today the clients and I discussed wider use of the test server, by a slightly wider body of users.

So, I think this has become more important.

Could you have a think about this please?  How about if:
1. We have VAL code that inspects the window URL, and looks for the text `VAL-DEV`.  
2. If that text is present, then the blue header bar goes to dark red, and the [VAL] in the title bar is changed to [VAL-DEV]

How does that sound?

Note: for this, we wouldn't just look for `VAL-DEV` in the server part of the URL, we'd look in the whole of the window-URL.  So, to test this, we'd just to a free-text search for `VAL-DEV`, and that would trigger the UI colors to change.  I think.'..

**Update:** user requested that we also have suitable clarifying signage on the login/welcome screen to.  Have demoted from `bug` to `enhancement` as this fix isn't urgent.

**Comment by TahaKhanAbdalli** [comment]
Hello, @IanMayo. 
We can set a `variable` in `.env` file. Which will be different for development and production environment. With the help of this variable we can change color of UI accordingly.

**Comment by IanMayo** [comment]
Sure, ok.  Let's do that.

**Comment by TahaKhanAbdalli** [comment]
> Sure, ok. Let's do that.
> 
> Do you think you can have it done by Monday lunch-time (UK hours)?

Sure.

**Comment by TahaKhanAbdalli** [comment]
In Development
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/98095003-dc0a-46c8-8d77-0334ad4619ef)

In Production
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/10f33bb0-0219-4ff6-ad9d-82e72671ae57)

Please confirm me is it okay?
In development, the UI color of complete app will be red and in the top Appbar the [VAL_DEV] will be shown.
In production, the UI color of complete app will be the default color of the app and in the top Appbar [VAL] will be shown.

**Comment by IanMayo** [comment]
Yes - that's a great solution.  I look forward to being impressed by how few lines of code it is!

**Comment by TahaKhanAbdalli** [comment]
Only 5 to 7 lines of code.

**Comment by IanMayo** [comment]
Re-open, since users want stylised welcome screen too (red backdrop and name of system)

**Comment by TahaKhanAbdalli** [comment]
Hi @IanMayo, 
Could you please give me an idea about this? If we add a red color to the background, it will look like this: I am just checking. Because I think it does not look better.
And also, where do I need to add the system name?
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/b31d47df-f675-4648-aaca-ae08e8570f32)

**Comment by IanMayo** [comment]
No - it's the login panel we need to style.  This is so that users recognise they are logging into the testing instance, and not the real instance (since they could have different accounts/passwords)

**Comment by IanMayo** [comment]
Oh, and it would be `Welcome to VAL-TEST`
