### ISSUE TITLE
Need to use soul-auth roles, not RCO

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#1080]
In our user table we have roles.

But, in the soul-auth permissions model, these are managed via entries in the `_user_role` table.

So, we need to change the UI of the `User` page to reflect this new model.  The UI will show the `roles` entries for this user, and  `power-users` should be able to change which `roles` a user has.

Hmm: `soul-auth` allows for multiple roles per user, so a set of permissions is `built-up`.  But, the permissions model we have implemented just uses one role instance for users and another for power-users, we don't accumulate them.  So, we _could_ "hide" the one-to-many relationship - i.e. Provide a drop-down of the two roles, and when it is modified, clear all `user_role` entries for that user, and just store the new one.

**Comment by IanMayo** [comment]
Oh, I'm hoping for something simpler than the above.

In the `items` table, each `item` can have multiple entries in an `itemCode` table - but that's hidden from users.

So, for the `UserShow` page we would include a component that shows the `user_roles` entries for this user.  In the `UserEdit` page we would include a multi-select list showing all of the entries in the `roles` table, marking the current `user-roles` as selected. On `Save` we would clear _user_roles_ for this user, and create new ones matching the current selection.

(maybe we only do the wipe/create if the roles control has been updated)

How does this sound?

**Comment by TahaKhanAbdalli** [comment]
Okay, I will follow this approach. Thanks, Ian.
