### ISSUE TITLE
Any user can set temporary password

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#1110]
Our requirement was that only rco-users and rco-power-users could set a temporary password for a user.

It was reported today that any user can set a temporary password for a user.

We should verify and resolve this issue.

**Update:** I've checked the software.  The implementation allows rco-users and rco-power-users to reset passwords.  It's `default users` that can't.

I believe the tester saw intended behaviour: when logged in as rco-user he was able to reset a password.

But, I'll double-check onsite tomorrow, in case a database configuration error mistakenly allows a default user to reset a password.

**Update:** VAL is correctly implemented, and there is no defect.  But, users aren't sufficiently aware of the intention of assorted roles. So, we should introduce a paragraph of explanatory text on the `Create user` and `Edit user` pages.   @TahaKhanAbdalli - if you create a PR with modified VAL that includes some placeholder text, then I'll go in and put in the correct text.

**Comment by TahaKhanAbdalli** [comment]
Hello @IanMayo,
Sorry for the inconvenience. I didn't understand the exact purpose of this issue. However, I have tested and found that the default user is not able to reset the password because the "Edit Password" button is only visible to the rco-user and rco-power-user.

**Comment by IanMayo** [comment]
Sure.  The tester thought that `rco-user` was `any user`, whereas, it is still a priviledged role.  He was unaware that `default-user` was the entry level set of permissions.

At least, I think that's the issue.

**Comment by TahaKhanAbdalli** [comment]
So, is it an issue that needs to be resolved, or should I ignore it as `rco-user` and `rco-power-user` already have this permission?

**Comment by IanMayo** [comment]
> So, is it an issue that needs to be resolved, or should I ignore it as `rco-user` and `rco-power-user` already have this permission?

Have updated description to clarify how we'll respond to this.
