### ISSUE TITLE
Login failure after creating new user

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#1111]
A user was doing some testing.

Whilst logged in as himself, he created a new user.

Then he logged out, and tried to login as the new user.

He got this error: `400: foreign key constraint failed`

I guess there is a chance there's something inconsistent in the way we create a new user, maybe to do with `user-role`.  Aah, but I think in the login process we may pull in some other data to populate the welcome screen - and when that fails it looks like a login failure.

**Update:** I don't get this behaviour for VAL on our `main` branch.  There is a chance I've omitted something in the database migration.  I'll investigate onsite tomorrow, and determine the exact REST call that trigged the error.

**Comment by TahaKhanAbdalli** [comment]
Hello @IanMayo,
I just tried to reproduce this issue and did not succeed.
The steps I followed to reproduce this issue are:

1. Logged in with the `rco-user`.
2. Created a new user.
3. Logged out from the app.
4. Tried to log in with the new user.
5. It allowed me to enter.
6. Updated the new user's password.
7. Logged out from the new user.
8. Re-logged in into the app with the updated password as the new user.
9. Everything is working fine.

**Comment by IanMayo** [comment]
Thanks @TahaKhanAbdalli - that matches what I saw. I suspect we have a missing/extra FK declared in the on-site database.  I'll try to reproduce the issue this morning, and see which REST call fails.  It's almost certainly not a software issue.

**Comment by IanMayo** [comment]
I can see the issue on the onsite database.   The error is `FOREIGN KEY constraint failed` (`SQLITE_CONSTRAINT_FOREIGNKEY`) for the POST to `audit` resource recording the new login.

**Comment by IanMayo** [comment]
Tested and verified.
