### ISSUE TITLE
Should not invite default user to accept receipt note

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#1113]
I'm logged in as a default user.

From the Welcome page I can see a list of Pending Receipt Notes.  If I click on the title, I am shown the list.

If I select one, I am invited to mark `Receipt Note Received`.  If I do that, the backend rejects the operation, and I get logged out.

This is evidence that the backend security is working, but the front-end shouldn't offer the action to a `default-user`.

**Comment by TahaKhanAbdalli** [comment]
Hello @IanMayo,
I have remove the buttons for default user. Now he cannot be able to perform any action related to `Receipt notes` and `Hastener notes` from frontend.
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/f098ceef-87e5-4739-a554-a3e8adf5a60b)

And also I just need your confirmation should we need to remove this `Pending Receipt Notes` box from welcome page for default user? 
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/310553d9-fb07-48b5-9b88-c91902b057d9)

**Comment by IanMayo** [comment]
Hello, it's ok - we don't need to remove that block from the Welcome Page, it can stay.
