### ISSUE TITLE
Batch Form: Year of receipt validation not working

### ISSUE THREAD

**Issue by salony75way** [DeepBlueCLtd/RCO#146]
Generate **Batch Number** showing NaN if we do not select  **year of receipt** in batch create form

![Screenshot 2023-04-19 at 6 58 07 PM](https://user-images.githubusercontent.com/45573884/233255858-d71154bd-25a9-43d4-87d8-276d63d37ff5.png)

**Comment by IanMayo** [comment]
Aah, @salony75way - so is the solution to make it mandatory in `BatchCreate` and `BatchEdit`?

**Comment by IanMayo** [comment]
I`ve had (another) play with this.  The `year of receipt` is mandatory, but the warning message doesn`t show.

Well, the user is told that the form is incomplete, but the user isn`t told which field is missing.

There _was_ an issue where the first batch for a year ended up with an invalid batch number - but that is now fixed.

**Comment by IanMayo** [comment]
This is now fixed.
