### ISSUE TITLE
Create central definitions of icons

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#150]
We have icons in the left-hand menu bar.

I would like to:
1. Declare the icons we use in RCO in a central file, maybe in `constants.ts`.  In there we will declare ICON_ITEM and assign a MUI icon to it.  With this in place, we only have to change the `item` icon in one place.
2. Extend use of the icons across other parts of RCO. This includes:
    *  adding the `item` icon to the `Items` tab in `BatchShow`
    * adding `project` and `batch` icons to the `Add` buttons on the welcome page
    * adding `batch` icon to title for the `Recent Batches` list on the home page
4.

**Comment by TahaKhanAbdalli** [comment]
Do I move the icons used everywhere to constants or just the ones mentioned in the issue?

**Comment by IanMayo** [comment]
I was just referring to the icons we use for resources.  Are there any others?

**Comment by TahaKhanAbdalli** [comment]
Yes there are for the `user menu` and for `buttons` etc.
