### ISSUE TITLE
Move Project fields to Batch

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#166]
Some of the details I provided for `Project` actually apply to a `Batch`:
- start date
- end date
- project code

Move these to `Batch` - include typescript types, data generation, forms and lists

**Comment by TahaKhanAbdalli** [comment]
Should I remove from `Project` Resource and add to `Batch`?

**Comment by IanMayo** [comment]
> Should I remove from `Project` Resource and add to `Batch`?

Yes please.

**Comment by TahaKhanAbdalli** [comment]
The `start` and `end` date of `item` depends on `start` and `end` date of `project`. What should be the `date range` of `item` if removed from `project`?

**Comment by IanMayo** [comment]
It will depend on the start and end date of the parent Batch.
