### ISSUE TITLE
Strategy for sensitive names

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#2]
The users require the contents of some drop-downs to be private.

They even require the names of some fields to be private.

We need a strategy for this.  I can think of these possibles:
* internationalisation resource file
* properties table in backend database, accessed at application load.

Ok, this seems straightforward. Just use the `i18n` that's built into `react-admin`:
https://marmelab.com/react-admin/Translation.html

We'll have a backend resource that reads a translations table.  This will be a series of key-value pairs, with the token-id in one column, and the text-to-use in the next column.

Initial translations would be for
- project
- project code

**Comment by topdev83** [comment]
I think that the best strategy is to store the private data in the backend database.
In this way, the private data can be secured and only accessed by authorized users.
Additionally, using a backend database will allow for easier management of the private data as more users are added to the system. 
This will also ensure that the private data remains consistent and accurate throughout the life of the application.

**Comment by IanMayo** [comment]
done
