### ISSUE TITLE
Database migration tasks

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#321]
This is a list of the steps we'll go through in the database migration, including techniques/strategies:

1. SQLite schema: treat the [RCOStore](https://github.com/DeepBlueCLtd/RCO/blob/main/src/types.d.ts#L127) as a database definition, create the DDL equivalent tables & relationships. Create an empty RCO2 SQLite database using the DDL
2. _When_ we get the legacy schema, create a RCO1 SQLite database of it.
3.  Populate RCO1 database, according to relationships
4. Migrate RCO1 content to RCO2, using these strategies:
    a. Map matching tables to each other, renaming fields as necessary
    b. _some strategy_ for legacy identifiers (See below)
    c. If necessary split some tables/combine others.
    d. If necessary split some fields/combine others.
    e. Where legacy content isn't being moved to new schema, find new table most related to the legacy table.  Create `legacyRemarks` field in that table, and pretty-print legacy content into those remarks.

### Strategy for legacy identifiers
Our legacy content will have id fields.  We  _could_ copy these, and use them as IDs in RCO2.  But, I think that will prevent us using autonumber fields in SQLite.  So, tables may require a `legacyId` column.  For foreign keys, we lookup the legacyId, then use the new id of that row as the foreign key.  I _think_ this means that foreign keys may have to start off as optional, then make them compulsory later in their life.

Have documented some migration tasks here:
![diagram](https://docs.google.com/drawings/d/e/2PACX-1vStfjQel4b7qkkbx7aaidl8deVjU-arNELaW4xF8LVfH6HMd6eOsTDhVwSL-46krH_xIiCCMi1Izzsn/pub?w=1144&h=1158)

**Comment by rnllv** [comment]
```
interface Audit extends RCOResource {
...
  activityType: AuditType
...
}
```

@IanMayo , this should be ActivityType.

**Comment by rnllv** [comment]
@IanMayo, I'm following standard naming convention for SQL to define the schema (mainly underscores in place of camelcase joint strings)

```
--Meta table - Activity Type
CREATE TABLE activity_type(
       id INTEGER PRIMARY KEY,

       name TEXT NOT NULL,
       label TEXT NOT NULL
);
```
```
--Resource table - User
CREATE TABLE user (
       id INTEGER PRIMARY KEY,

       name TEXT NOT NULL,
       password TEXT NOT NULL,
       admin_rights INTEGER NOT NULL,
       active INTEGER NOT NULL,
       roles TEXT NOT NULL, /*Should be a json array string. Ex.: "['rco-user', 'rco-power-user']" or "['rco-user']" or "[]"*/
       staff_number TEXT NOT NULL,
       departed_date TEXT,

       created_at TEXT NOT NULL,
       created_by INT NOT NULL,
       FOREIGN KEY (created_by) REFERENCES user(id)
);
```
```
--Resource table - Audit
CREATE TABLE audit (
       id INTEGER PRIMARY KEY,

       user_id INTEGER NOT NULL,
       resource TEXT NOT NULL,
       data_id INTEGER NOT NULL,
       activity_type_id INTEGER NOT NULL,
       date_time TEXT NOT NULL,
       label TEXT NOT NULL,
       activity_detail TEXT,
       security_related INTEGER,
       subject INTEGER,
       FOREIGN KEY (user_id) REFERENCES user(id),
       FOREIGN KEY (subject) REFERENCES user(id),
       FOREIGN KEY (activity_type_id) REFERENCES activity_type(id)
);

```

**Comment by IanMayo** [comment]
yes, that's fine.

**Comment by rnllv** [comment]
@IanMayo, here's the first draft of the RCO2 sqlite DB schema: [RCO2.sqlite.zip](https://github.com/DeepBlueCLtd/RCO/files/11625146/RCO2.sqlite.zip)

**Comment by rnllv** [comment]
We'll need to ensure either using a transaction block or declaring [foreign key enabled pragma](https://www.sqlite.org/pragma.html#:~:text=PRAGMA%20foreign_keys%20%3D%20boolean%3B,no%20pending%20BEGIN%20or%20SAVEPOINT.) in the client code to ensure foreign key constraints are respected.

**Comment by IanMayo** [comment]
> Strategy for legacy identifiers

@rnllv  - are you aware of any best practices for handling legacy IDs during a database migration?

I've tried to explain the issue above, but please say if the explanation is insufficient.

**Comment by IanMayo** [comment]
Aah, @rnllv - one oversight in the SQLite table design.  `reference_item` is actually a table style that is used in multiple real table instances.

Hmm, there may not actually be any tables that match `reference_item`, they all seem to be instances of `active_reference_item`:
https://github.com/DeepBlueCLtd/RCO/blob/main/src/types.d.ts#L133

These will need to be declared as tables in the SQLite database. They are typically the lookup/reference tables shown on the right here: https://docs.google.com/drawings/d/1SYIb0PZxcabvhXdNMAEHlbdWaoam2ipB7x5ZUudVVGc/edit?usp=sharing

https://github.com/DeepBlueCLtd/RCO/blob/main/src/types.d.ts#L133
