### ISSUE TITLE
Dispatch list filters

### ISSUE THREAD

**Issue by salony75way** [DeepBlueCLtd/RCO#338]
Toggle filter doesn't work with nullable fields.

- Not dispatched (dispatchedAt is undefined/null),
- Receipt not received (receiptReceived  is undefined/null)

**Updated objectve**:
* [ ] introduce "Filters" for dispatches and destructions
* [ ] Introduce "Dispatched", "Not dispatched", "Receipt note pending" toggle filters for dispatches

Related issue: #334

**Comment by salony75way** [comment]
Yes @IanMayo  its still an issue, I am working on it.

**Comment by IanMayo** [comment]
Hello @TahaKhanAbdalli - have updated objective for this issue
