### ISSUE TITLE
Test bridging table entries created for `Save and clone`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#463]
When adding items to a batch, we allow the user to save/create and create a clone of the current item.

Since creating the `clone` behaviour, we now use `bridging tables` to allow multiple cat-code, cat-handle and cat-cave values to be specified.

Trial creating an item with multiple values for these, then create/clone and add another item with slightly different protection values.

Check that new bridging table entries are created for the two different items.

Note: I've just tested this. When we do `Create/Clone` the `code, handle, cave` fields for the previous item get duplicated:
![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/4785e413-b223-4ae6-8e7b-70dedd0cd5ab)

**Comment by TahaKhanAbdalli** [comment]
I have tested this and found similar behaviour that the new values `cat-cave, cat-handle, cat-code` are duplicated for the previous `item created`.
