### ISSUE TITLE
getList function of soul dataProvider is not getting correct filter value in param

### ISSUE THREAD

**Issue by TahaKhanAbdalli** [DeepBlueCLtd/RCO#494]
`LocalForage dataprovider` from `main` is running smoothly in conjunction with filters supplied through `ReferenceInput` but when we select from `ReferenceInput` while on `soul dataprovider` the filter provided is always 1 

**Steps to reproduce:**

1. Use soul dataprovider
2. Go to itemList page
3. Toggle on vaultLocation filter
4. Select `vaultLocation:30` 
5. Check the network tab. The network call has the filter `vaultLocation:1` instead of 10

Repeat the same for main branch and the filter will work as expected. The dataprovider in soul is in accordance to the documentation provided by `react-admin`. Provided here: [Writing A Data Provider
](https://marmelab.com/react-admin/DataProviderWriting.html#example-rest-implementation)

**Comment by IanMayo** [comment]
Fixed here: https://github.com/DeepBlueCLtd/RCO/commit/90268e4fe5769898dae1d6f235e4fb8129b432fb
