### ISSUE TITLE
Operators required for REST backend

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#504]
We need to handle filtering operators in `soul` as we are using custom filtering operators in our `react-admin` application. Following is the list of the spotted filter operators:

- [x] _eq
- [x] _neq
- [x] ~~q (This versatile search filter allows matching any record within the SQLite table, regardless of the field, providing comprehensive search capabilities for your data.)~~. @TahaKhanAbdalli reported that `_search` fill requirements of `q`.
- [x] lte
- [x] gte
- [ ] ~~comparison with undefined value e.g. `filter={{ receiptReceived: undefined }}`~~  **Note: hopefully we can remove instances of `undefined`**. See [below](https://github.com/DeepBlueCLtd/RCO/issues/504#issuecomment-1649396459)
- [x] comparison with null value e.g. `filter={{ receiptReceived: null }}` [issue created](https://github.com/thevahidal/soul/issues/105)

**Comment by IanMayo** [comment]
Hmm, can we combine undefined/null?   I _don't think_ a REST API should think about different values for them.  Does react-admin give queries for both of these?  If it does, then I wonder if that's actually an issue with our RCO code.

**Comment by IanMayo** [comment]
I _Think_ that `_search` is the equivalent of `q`:
https://github.com/thevahidal/soul/blob/main/docs/api/rows-examples.md

Will have to play with an instance of Soul, to find out.

**Comment by TahaKhanAbdalli** [comment]
React admin does not give it, we explicitly provided it at some places for some field to be undefined in the filter. We don't have for null values in our code, but we or someone may need in the future for null values also

> Hmm, can we combine undefined/null? I _don't think_ a REST API should think about different values for them. Does react-admin give queries for both of these? If it does, then I wonder if that's actually an issue with our RCO code.

**Comment by TahaKhanAbdalli** [comment]
> I _Think_ that `_search` is the equivalent of `q`: https://github.com/thevahidal/soul/blob/main/docs/api/rows-examples.md
> 
> Will have to play with an instance of Soul, to find out.

I'll try that.

**Comment by IanMayo** [comment]
@TahaKhanAbdalli - can you help us with this on the front-end please?

I'd like our front-end data to be consistent with the backend, so we don't have to compare against both `null` and `undefined`.

I _guess_ the solution to this is to remove optional fields, replacing them with compulsory fields with type `<value> | null`.  There would also be a fair amount of new JS code to set previously optional fields to `null`.

**Comment by IanMayo** [comment]
Actually @salony75way - I'll get you on this, please.

Our SQLite backend will return `null` for empty attributes, but the mock backend uses `undefined`.  I don't want us to have to check for both. So, I'd like us to change `types.d` so that won't have any optional `?` fields - we declare that they are of the relevant type, or `null`. Then our frontend code will be consistent across both backends.  This will probably involve quite a lot of work in the data generation elements.
