### ISSUE TITLE
SQLite database has `integer` for `dataId` in `Audit`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#525]
Some of our tables have an integer PK, and some tables that came from legacy data have a string PK.

The `Audit` table can optionally store the ID of a the item that is being reported upon, in the `dataId` field.

But, our SQLite schema says this is an integer.  In truth it could be a string.

I _expect_ SQLite won't mind either way.  But, we should test that SQLite Audit logs are successfully maintained when we, for example, mark a `catCode` as not- active.  We should check the SQLite data, and check how the history is presented for that `catCode`.

**Comment by TahaKhanAbdalli** [comment]
Upon testing with multiple resources with string id (catCode, catCave, catHandle, Organization, Department), it is found that the correct `dataId` is being referenced in the `audit table`. Be it a `string` or `number` id, the `database` is storing the correct `dataId`. @IanMayo

**Comment by IanMayo** [comment]
Great, thanks @TahaKhanAbdalli
