### ISSUE TITLE
Increment Consect counter on clone item

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#542]
Consect/Pages will probably either contain a document reference (typically with a consecutive counter), a number of pages, or the acronym LEP.

When it's a document reference, frequently these will have a year number and a counter. These are samples of :
* 12/2023
* 12/23
* 040-23
* ARCH-32
* 1
* 01
* 12
* 035
* DDD 02
* 8888 <-  this is a system ID
* CON12/22
* EDR 12/22
* 1 of 8

I think we can match (and increment these patterns).  It's the **bold** item that would be incremented:
* **12**/2023
* **12**/23
* **040**-23
* **1** of 8
* CON**12**/22
* EDR **12**/22 <-- in the above cases, if there are two integers present, increment the first
* ARCH-**32**
* DDD **02**
* **1**
* **01**
* **12**
* **035** <- in the above cases, if one integer less than 1000 is present, increment it
* 8888 <-  this is a system ID, do not increment standalone numbers greater than 1000

We could do with a clever regexp to see if there is an integer in the string that is under 2000, and to increment it.

With this algorithm, we can modify `Save/Clone` to have a go at incrementing the Consect.  Users may end up writing over it, but it could that for 50 items, it _just-works_;

This snippet:
```
function incrementFormat(input) {
  return input.replace(/(\D*)\b(\d{1,3})\b/, (match, other, num) => {
    return other + (Number(num) + 1).toString().padStart(num.length, '0');
  });
}
```

(Test [here](https://jsfiddle.net/xh9aso5b/4/))

Generates these outcomes:
```
old: 12/2023
new: 13/2023
-----------
old: 12/23
new: 13/23
-----------
old: 040-23
new: 041-23
-----------
old: 1 of 8
new: 2 of 8
-----------
old: CON12/22
new: CON12/23
-----------
old: EDR 12/22
new: EDR 13/22
-----------
old: ARCH-32
new: ARCH-33
-----------
old: DDD 02
new: DDD 03
-----------
old: ANOTHER 07
new: ANOTHER 08
-----------
old: NEW-123
new: NEW-124
-----------
old: 1
new: 2
-----------
old: 01
new: 02
-----------
old: 12
new: 13
-----------
old: 035
new: 036
-----------
old: 0001
new: 0001
-----------
old: 0999
new: 0999
-----------
old: 1000
new: 1000
-----------
old: 8888
new: 8888
-----------
```

**Comment by IanMayo** [comment]
@salony75way - I think we have an issue.  A value like `2023/5` doesn't update to `2023/6`.  It works in the fiddle [here](https://jsfiddle.net/xh9aso5b/4/)

But, the regexp in this PR is slightly different.

**Comment by salony75way** [comment]
> @salony75way - I think we have an issue. A value like `2023/5` doesn't update to `2023/6`. It works in the fiddle [here](https://jsfiddle.net/xh9aso5b/4/)
> 
> But, the regexp in this PR is slightly different.

Yes i have modified this regex as there was an issue with build build related to SonarCloud. I will check this " A value like 2023/5 doesn't update to 2023/6" issue.
