### ISSUE TITLE
Custom route authorization needs a page reload

### ISSUE THREAD

**Issue by TahaKhanAbdalli** [DeepBlueCLtd/RCO#551]
The authorization for custom routes in React Admin can be managed using the `WithPermissions higher-order component` (HOC) as explained in docs: [restricting-access-to-content-inside-custom-pages](https://marmelab.com/react-admin/doc/2.9/Authorization.html#restricting-access-to-content-inside-custom-pages). This HOC allows you to `restrict access` to content inside `custom pages` based on the `user's permissions`.

Our implementation of authorization for custom routes has a `bug` that arises when we switch user roles without `refreshing` the page. For example, if a user logs out from one role (e.g., "rco-power-user") and logs in with another role (e.g., "rco-user"), the `permissions` of the new role don't take effect immediately. This is because the permissions are fetched only once in `app.tsx createRoute` component during the initial rendering of the custom route, and they remain unchanged even after the user switches roles.

To fix this issue, we need to ensure that the permissions are re-evaluated whenever the user role changes. To achieve this, we need to be using the `WithPermissions` component in the custom route. The WithPermissions component allows us to fetch the user's permissions dynamically whenever the component is rendered.

**Comment by IanMayo** [comment]
Aah, I see.  I gave [feedback](https://github.com/DeepBlueCLtd/RCO/issues/293) that it looked like `permissions` was being checked too often.

Maybe the fix for that introduced this issue.

**Comment by TahaKhanAbdalli** [comment]
No, I don't think that caused this issue. That particular issue is fixing the side menu calling the permissions.

**Comment by TahaKhanAbdalli** [comment]
This is no longer an issue. It's fixed by `Salony` in this [commit](https://github.com/DeepBlueCLtd/RCO/commit/0381d878456f0825f7d38871ca12ad9f94e8c4d7). For testing:

1- Login as `power-user` 
2- Go to `Vault Location`
3- See the `create` button at the top (available for `power-users` only)

4- Logout (Don't reload the page and don't change the tab)

5- Login as simple `user`
6- Go to `Vault Location`
7- No `create` button at the top 

@IanMayo

**Comment by IanMayo** [comment]
Agreed. Working
