### ISSUE TITLE
Complete Authentication Process diagrams

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#634]
We have a diagram documenting the authentication process.

It needs to have an extra sections for `logout` and for `revisit` to be added to `Login`.

It should also document the user document being stored in a time-expiring cookie, instead of localStorage.

**Comment by TahaKhanAbdalli** [comment]
The flowcharts for `revisit` and `logout` are completed. If no further task remains, should I close this issue? @IanMayo

**Comment by IanMayo** [comment]
to allow an effective review, could you please include the name of the encryption functions we're using/intend to use, so the stakeholders can review them please?
(not the js function, but the type/name/level of crypto were using)

**Comment by TahaKhanAbdalli** [comment]
We are using `crypto-js` library with `AES` encryption algorithm on the frontend side.

**Comment by IanMayo** [comment]
Could you insert `AES` reference in the relevant bpxes in the diagrams, please @TahaKhanAbdalli ?

**Comment by TahaKhanAbdalli** [comment]
Done

**Comment by TahaKhanAbdalli** [comment]
Should we close this? @IanMayo

**Comment by IanMayo** [comment]
Subsumed into #735
