### ISSUE TITLE
Fix filters for `destroyed` and `dispatched`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#645]
In the current develop branch we're using the presence of a value in `dispatch` or `destruction` as indicating an item has been dispatched or destroyed.

It's the presence of values in `dispatchDate` or `destructionDate` that is the _actual_ indicator of dispatched or destroyed.

https://github.com/DeepBlueCLtd/RCO/pull/474/files/657dc65bfc1b023c01cccb90c97822ad5efa298e..ddf31e26d5200c89d8d530538603bf892b8ddfe3#diff-c0c1cdeb550e7c034692ee2b6d083e86289daa261331ca186aad99be42fd8fe3

**Comment by TahaKhanAbdalli** [comment]
@IanMayo This is working fine. If you see the `BooleanFilter`, the filtered is being applied on the basis of `fieldName` i.e. `dispatchedDate` and `destructionDate`. The `source` is being used for getting the ids only.
