### ISSUE TITLE
Allow for search in `remarks` column

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#669]
Some legacy data is in patterns that we don't support in VAL.

One such pattern the ability to attribute a batch to multiple projects.  This has happened on 8 occasions over time, though none in recent years.  7 batches refer to 2 projects, and one refers to three.  Most of the multiple instances represent mistaken duplication.

But, a couple are valid.

We're going to delete the multiple instances, so there is just one.  But, we need to copy the project names into the Batch remarks column, so it can still be accessed.

To allow the batches to be found via project name, we need the `Batch` `remarks` column to be searchable via text search.

Check that our mock data generation generates some remarks for batches.

Introduce functionality to `BatchList`, and check we can search for the content.

**Comment by TahaKhanAbdalli** [comment]
After `testing`, I've found that our `system` can search for `remarks` and `references` in both our `mock` data and the `SQLite` dataset using `text-based` search.

**Comment by IanMayo** [comment]
Thanks @TahaKhanAbdalli .  In the real dataset there are 125k items - it could be much slower doing a full-text-search across the whole dataset vs over the `remarks` column.   Aah, hold on - this is just for batches, that's just 4k items.

Could you give me an example of the SQL that gets run for the full text search?   I'll run it against the target data, and check it responds quickly enough.

(you may have to do some digging in `Soul` to get the answer to that, sorry).

**Comment by TahaKhanAbdalli** [comment]
SELECT * FROM batch
WHERE
    (batchNumber LIKE '%carrot%' OR
    yearOfReceipt LIKE '%carrot%' OR
    organisation LIKE '%carrot%' OR
    department LIKE '%carrot%' OR
    remarks LIKE '%carrot%' OR
    receiptNotes LIKE '%carrot%')

**Comment by IanMayo** [comment]
Ian to test above query against target database

**Comment by IanMayo** [comment]
I was nervous about the free-text-search, since it is running in every field of every row.  But, in DBeaver it searches through 125k rows in 170ms.  That's great news. Issue resolved :-)
