### ISSUE TITLE
Bug - Live Items showing destroyed or dispatched items

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#675]
I have destroyed/dispatched some items, but they are still shown in `LiveItems` (with mock backend).

Note: this works satisfactorily for real backend.

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/dcac6fa3-1597-48fc-b00e-7682a2febeff)

I have checked the `LocalStorage`, and can see that the `dispatchedDate` and `destroyedDate` fields do have values.

**Comment by TahaKhanAbdalli** [comment]
@IanMayo  I'm unable to reproduce this `bug`. I have `dispatched` and `destroyed` items and they don't show up in live items list.

**Comment by IanMayo** [comment]
> @IanMayo I'm unable to reproduce this `bug`. I have `dispatched` and `destroyed` items and they don't show up in live items list.

ok, and that's with mock data in `localStorage`?

**Comment by TahaKhanAbdalli** [comment]
Yes

> > @IanMayo I'm unable to reproduce this `bug`. I have `dispatched` and `destroyed` items and they don't show up in live items list.
> 
> ok, and that's with mock data in `localStorage`?

**Comment by IanMayo** [comment]
Sure, ok. Thanks for investigating.
