### ISSUE TITLE
Not showing VAULT for dispatch using old (legacy) vault

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#710]
I'm usingt the SQLite backend.

We have 2 dispatches in the test data.  One has `vault` of `VAULT` the other has `vault` of `LEGACY`.

When I view the dispatch for `LEGACY`, the value for `vault` isn't shown, and a console error is shown.
![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/aea67baf-4f68-4d76-81ea-e66e38d0a87f)

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/67ddbbd9-997b-4073-bcc5-907273b01dfa)

**Comment by TahaKhanAbdalli** [comment]
The issue is because we can only assign `active vaults` to `dispatch`. Due to inconsistency in data, the `LEGACY` which is inactive is assigned to dispatch, therefore causing the error. @IanMayo

**Comment by IanMayo** [comment]
We have that constraint for adding new items.

We shouldn't apply that constraint when viewing items.
