### ISSUE TITLE
Error creating new project

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#716]
We need to add `enduring` to the new Project Form:
![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/2dcbaaf6-68da-41a1-8c72-89b556001ee9)

**Comment by TahaKhanAbdalli** [comment]
We had a requirement because of which the `enduring` is not offered on `create`. It is offered on `edit`. `Active` field is not present at all, which also throws error.

![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/efc537cc-e5b4-4c58-97e1-1dc56af40824)

**Comment by IanMayo** [comment]
Ok. Let's include `Enduring` in the create form, set to `False`.  Let's have a hidden `active:true` field too, please.
