### ISSUE TITLE
High volume performance tests

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#728]
I have introduced a large copy of the database, with proportions similar to the target dataset.

We should:
* [x] introduce new start command that runs `Soul` with the large database
* [ ] do some performance tests, to include:
    * [x] searching across all items 
    * [x] filtering across all items
    * [x] filtering across all items for project/platform (since these are being pulled in via a SQL View)
    * [ ] searching across all platforms, projects

**Comment by TahaKhanAbdalli** [comment]
Format of `Destruction` and `Dispatch` dates in the new data is not correct and it displays `Invalid Date` on frontend

**Comment by IanMayo** [comment]
Testing complete (using real data)
