### ISSUE TITLE
Can't edit existing vault location

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#732]
I don't have access to the bulk dataset from here, so I can't run it against bulk - the issue doesn't happen in the normal dataset.

But, here is the issue:
- I view an item
- I see the vaultLocation (P45)
- I click on `Edit`
- The `vaultLocation isn't set to P45 - possibly because it has only retrieved first 25 rows of vaultLocation

If I type `P45` in the drop-down doesn't do a round trip to see if there is a location called `P45`.  I _Thought_ react-admin did this in other forms.

**Comment by TahaKhanAbdalli** [comment]
This is a `system-wide` issue, we have done it in many palces either by `hard-coding` number of rows or by using default 25 rows.

**Comment by IanMayo** [comment]
I _Think_ I have seen in other places, that when I (as a user) starts to type, RA sends a wildcard search to the backend to retrieve matching items.

**Comment by IanMayo** [comment]
This is done.
