### ISSUE TITLE
Update startup commands

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#747]
While `yarn serve` was our standard startup command, and `yarn serve:soul` was the new version to start with RCO embedded in Soul, the use of soul is now the standard strategy.

We will still need a command to start Soul without extensions, used for development.  So, introduce `yarn serve:dev`, that starts Soul, looking at the correct database, but without the extensions provided.

Also rename `yarn serve:soul` to `yarn serve` and `yarn serve:soul:mock` to `yarn serve:large`.

We will also need to update the 2 soul-based installation wiki scripts to use the new commands.

We will also need to update the root README.md.

**Comment by TahaKhanAbdalli** [comment]
We may  also need large data set for development purposes without serving our frontend like `yarn serve:dev`

**Comment by IanMayo** [comment]
Yes, I'd considered that, but was too lazy to record it 🤣 .  Thanks for highlighting it.
