### ISSUE TITLE
Avoid requirement for VITE_URL

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#756]
The VITE_URL in `.env` lets us specify the path to the Soul backend.

Now that we are hosting RCO within Soul we don't need the backend URL to be specified, we should be able to determine it from the current URL.

Note: it won't be acceptable to have this as localhost.  We need to test it from another device, so it's a none-localhost URL.

Note2: we _may_ need another strategy for when we wish to separate the two server processes, in dev mode.

**Comment by TahaKhanAbdalli** [comment]
Should we close this issue? @IanMayo

**Comment by IanMayo** [comment]
Yes, done.
