### ISSUE TITLE
Value not shown for `Projekt` in Batch Details page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#770]
I can't reproduce this in the version of RCO published here from `develop`.

But, I think I understand the issue.

From the backend database on the client network, the config data sets the label of `project` to be `projekt`.

For the `BatchList` page, it is showing the value for the field named `project`, but shows a column label as `projekt`.

But, when I go into `BatchShow` the `project` control (labelled `projekt`) is empty.   From dev tools I can see that the database provided a valid value of `project` for this batch.  My guess is that `BatchShow` is trying to display the value of a field named `projekt` (instead of `project`).

I hope this all makes sense.  I can investigate using SQLite backend once I'm back at a dev machine.

Ahh, hold on. I've inspected the `rest` a bit.  There aren't any projects that are `active` or `enduring`.    It may be an issue with the data in SQLite. I'll have to investigate that.

Aah, this may be part of the issue. For `BatchEdit` we should include all Projects in the `Project` dropdown.  It's `BatchAdd` where we limit it to enduring projects or the most recent ones.

Hmm, when I inspect the REST calls as the `BatchShow` form is displayed, I see these familiar items:
* `batch\rows\500` (to get the data for this batch)
* a series of `projects/rows/` calls for project, platform. vault, organisation, department, user
*  `projects/rows/` call, filtered by enduring, active, endDate
* `platform/15` to get the label for the current value of platform
* `organisation/BBC` - more labels
* `vault/LEGACY` - more labels
* `department/stores` - more labels
* I see that we don't send out a call for the label for the `project`.

I hope that helps to explain what is happening :-D

**Comment by TahaKhanAbdalli** [comment]
For `Batch Edit` it's showing all the projects and for `Batch Create` it only shows active.

**Comment by TahaKhanAbdalli** [comment]
And the other issue `BatchShow is trying to display the value of a field named projekt (instead of project)`, I don't see this issue. Maybe, it's the data that's causing the problem

**Comment by IanMayo** [comment]
> And the other issue `BatchShow is trying to display the value of a field named projekt (instead of project)`, I don't see this issue. Maybe, it's the data that's causing the problem

Yes, it's the data, but I'm pretty sure we need to support that pattern in the data.  Let me try to produce some suitably mangled data.

**Comment by IanMayo** [comment]
This seems to be working ok now.
