### ISSUE TITLE
Remove `Password` field for `Edit User`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#786]
Our process for forgotten passwords is for a power user to reset the password.

So, we don't ask for a password when adding a new user, and we don't have a password control when editing a user.

@IanMayo to check if they have `active` field in their database.  If they don't remove it from our SQLite schema and mock datasets.

**We need to remove user.active from the backend and schema definitions**

**Comment by TahaKhanAbdalli** [comment]
Should I remove `password` field for `add user` also?

**Comment by IanMayo** [comment]
> Should I remove `password` field for `add user` also?

Yes, certainly, please.

**Comment by IanMayo** [comment]
We also have an issue with `active`.   It's present in the backend database, and it takes a valid value.  But, since it's not in the schema, we _know_ it's not being used in `RCO`.

So, I guess the answer is to remove it from the backend.
