### ISSUE TITLE
Ensure no users can delete items

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#801]
Our UI does not include delete buttons for any types of resource (things can only be made not active).

But, our permissions table doesn't explicitly deny power-users from being able to delete things.  We should explicitly state that in the data, to ensure that in future maintenance a `delete` button isn't accidentally left enabled

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/9f2efd63-5831-4a91-afbf-7c45411339c9)

**Comment by TahaKhanAbdalli** [comment]
How can we restrict the `power-user` from deletion because there's nothing on the frontend that allows deletion? If we do want to restrict the deletion it should be done from backend. Restricting on the frontend doesn't make any sense (though it's already restricted).

**Comment by IanMayo** [comment]
Sure.  I _guess_ it's to help with future maintenance/development.  If a control/page is added, and `delete` record is accidentally left in the UI, then I'd like the data-provider to throw an error, revealing our policy that nothing can be deleted.
