### ISSUE TITLE
Correct logic for users-with-loans on Welcome page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#802]
On the welcome page we show a list of users who have items on loan.

It is not showing valid data, it is only showing a subset of the data.

Here is the code:
![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/1c085c3c-42c4-4d2b-bcb9-d83ed7af5ee0)

It fetches the first 5 loaned items, and produces a list of values in the `loanedTo` column.

That's not correct.  We should actually fetch all data that has a value in the `loanedTo` column (if we need to specify a maximum number, please use `1000` [*]).  Then we should summarize that data to get a list of unique ids.

[*] This is getting quite a lot of data.  I know `soul` allows a `schema` field which allows the specific required columns to be specified.  But, I don't know if/how we would pass that through our `react-admin` `DataProvider`

https://github.com/thevahidal/soul/blob/main/docs/api/rows-examples.md#1-list-rows-of-a-table

**Comment by TahaKhanAbdalli** [comment]
You can continue. I started it but I'll do some other task then. Thanks.

**Comment by IanMayo** [comment]
Fixed in #811
