### ISSUE TITLE
Need to allow a user to have no role in `Edit User` form

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#803]
Our form validation for `Edit User` requires the role to be one of `rco-user` and `rco-power-user`.  It should allow an empty field.

**Comment by TahaKhanAbdalli** [comment]
Our database has `role` as `Non-Nullable`

**Comment by IanMayo** [comment]
Sure. Will update database, and ping it back to you.

**Comment by IanMayo** [comment]
Ok @TahaKhanAbdalli - backend change done.  Over to you.
