### ISSUE TITLE
Fix to list of users with items on loan

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#812]
On the welcome page we show a list of users with items on loan.

To do this, we pull a list of all items on loan from the backend, and collate a list of unique user ids.

While this effectively still happens in an instant, it involves a lot of data (the full details for 500 items are pulled to the client), and _could_ bring unnecessary loading on the backend.

Instead, we could define a SQL view that contains a list of users with items on loan. We could even count the items on loan.

Then the `On loan` listing on the home page would just be a summary of this view.  There could be 20+ users with items on loan.  So, allow list to take full right-hand column of welcome page.  We should also present this list in ascending alphabetical order.

Here is the SQL:
```
CREATE VIEW loanItems AS
SELECT
  COUNT(i.id) as numItems,
  i.loanedTo as userId,
  u.name
from 
  item i
INNER JOIN "user" u ON
  i.loanedTo = u.id
GROUP BY
  u.name,
  i.loanedTo
```

We can call the view "loanUsers"

Aah, we have to `mock` the `VIEW` in JS.  Let's just run through the data once, on page load.  If in the mock JS there aren't any items on loan, we should loan a few.

**Comment by TahaKhanAbdalli** [comment]
We don't have id field in this `view`, this will cause issues.

**Comment by IanMayo** [comment]
We have the user id:
![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/ff713ad9-7ed2-4c09-9b73-d90ed8aa5b85)

**Comment by TahaKhanAbdalli** [comment]
This is the error I get 
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/04dac168-9051-49c8-b01f-aa5e939c3bf7)

**Comment by IanMayo** [comment]
Oh, I see.  I'm sure I can fix that.  I've just experimented with modifying the view to show `loanedTo` as `id`.

But, I can't provide a new version to you until I'm back at a dev machine.
