### ISSUE TITLE
Switch cave and handle in target data

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#827]
I have confused the concepts of `cave` and `handle`.  Each contains items from the other.

The tables can be renamed (including the linking tables), but note that some foreign keys will need to be fixed, too.

We will also need to swap the placeholders in the ItemShow form.

**Comment by TahaKhanAbdalli** [comment]
Rename as in swapping `cave` and `handle` names?

**Comment by IanMayo** [comment]
> Rename as in swapping `cave` and `handle` names?

For now, we just swap the location of the two components.  Their names stay the same.  So - `itemHandle` will be in the 3rd position and `itemCave` in the 4th position.

**Comment by TahaKhanAbdalli** [comment]
itemHandle` is already on 3rd position?

![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/8abb8cd1-8d25-459a-bcf7-e9887401a9ba)

**Comment by IanMayo** [comment]
Aah, it's the content of the list that is wrong.  I can fix that without a software change :-D

**Comment by IanMayo** [comment]
Close. Include in #829
