### ISSUE TITLE
Cannot `Return` an item that has been `Dispatched`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#835]
In the `All Items` listing we show items that have been dispatched.

When one is selected, user should be able to select `Return` from the toolbar.  It's currently disabled.

The `Return` logic is this:
- clear `dispatchJob` field
- clear `dispatchedDAte` field
- create audit log for item, with activity type as `VAUL` (to indicate something being returned to the vault)

**Comment by TahaKhanAbdalli** [comment]
The logic is already there. Only the `button` condition needs to be fixed. I'll create the `PR` to show what logic is already implemented and if the change is needed in the logic I'll change accordingly.

**Comment by IanMayo** [comment]
> The logic is already there. Only the `button` condition needs to be fixed. I'll create the `PR` to show what logic is already implemented and if the change is needed in the logic I'll change accordingly.

Yes, I thought so.
