### ISSUE TITLE
Need headers and footers on reports

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#848]
For the assorted reports we should put a protective marking in the headers and footers of each page.

The value for this should come from a new `headerMarking`  in the `ConfigData` structure (and in SQLite).

I can do the SQLite change.

(small task, but I don't think we've worked with headers/footers before. Would like it to be done for pilot phase so staff can print/issue actual reports)

While we're doing this, it would be good to include these two items please:
* [ ] Page border for reports looks like it's currently 2,5cm. Could we reduce it to 1cm please?
* [ ] Staff can print `Muster Lists` for multiple users, or for multiple vault locations.  Could the page count be per user/per vault-location (if possible). Then the document for one user/vault-location is consistent with itself.

**Comment by TahaKhanAbdalli** [comment]
Waiting on you to first make the `SQL` changes @IanMayo
