### ISSUE TITLE
Token should get erased on `Logout`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#853]
I'm running `yarn dev` locally.

I logged in as 20300.

I then logged out, so the `Login` screen was visible.

I then killed the process in the terminal.

I then was able to log into RCO.  Things were broken, but the I was able to see data on the welcome page.

My _guess_ is that the password was verified against the stored token, and I was let in.

It _looks-like_ we should wipe the token on `Logout`.

This is possibly related to #735

**Comment by TahaKhanAbdalli** [comment]
The `token` is being wiped out. The reason why you could `login` is that the `page` was `cached` by the `browser`. And if you `refresh` without running the process again the page will `crash.`

**Comment by TahaKhanAbdalli** [comment]
Yes
