### ISSUE TITLE
Count missing from muster lists

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#869]
We have two types of muster list:
- user muster list
- vault location muster list

Beneath each listing is a count of the number of instances of each Protective Marking in that list.

There is an intermittent fault, where the count is empty.

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/5d616d54-30ad-498c-9086-bf1e30506c73)

After a refresh, frequently the issue goes away:
![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/253600df-a1c1-40bd-a50d-72704ce3e6e4)

**Comment by TahaKhanAbdalli** [comment]
I am not able to reproduce this on `vaultLocation` and on user muster list I don't see this table @IanMayo 

![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/612e2580-d37d-4cc6-b316-ff10e54d3f4a)

**Comment by IanMayo** [comment]
Aah.  You're right. It's not on User Muster List - just Vault Location Muster List.

I can normally repeat it by doing a hard refresh in the browser.

**Comment by TahaKhanAbdalli** [comment]
After hard refresh I am still able to see the count on first render.

**Comment by IanMayo** [comment]
Aah, it's ok with mock (JS) data, but missing with SQLite backend.

Here is the deployment for the "new prefix" issue: https://rco-review-pr-873.herokuapp.com/#/vaultLocation?displayedFilters=%7B%7D&filter=%7B%22active%22%3Atrue%7D&order=ASC&page=1&perPage=10&sort=id

On it, if I do a hard-refresh of browser, the next time I open a vault muster list, the table is empty.

**Comment by TahaKhanAbdalli** [comment]
Found it!

**Comment by TahaKhanAbdalli** [comment]
Unfortunately, I can't reproduce it on `development` server but it's there on `production` server?
