### ISSUE TITLE
Some rows missing from muster list at page break

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#876]
In print preview, some items are missing from the User Muster List.  I've seen the same behaviour on the Vault Location Muster list.

I did this by loaning blocks of consecutive items to myself.  At the page breaks, sometimes an item is missing.

I guess we need to insert some whitespace, somewhere.

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/82291ffa-61fa-45ac-adde-8e5b31aa01de)

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/c3974459-22e1-49f8-8b39-92e1c0b83bc4)

**Comment by TahaKhanAbdalli** [comment]
I couldn't reproduce this. Can you specify which `browser` you're using or what is the `zoom` level that you are using?

**Comment by IanMayo** [comment]
Sure. To reproduce it, I did have to loan loads of books to myself.

I spotted it onsite using MS-Edge, but the above screenshots were with Chome.

Let me update SQLite so I have lots of loaned book.

**Comment by TahaKhanAbdalli** [comment]
I couldn't reproduce this. Can you specify which `browser` you're using or what is the `zoom` level that you are using?

**Comment by IanMayo** [comment]
I've attached a PDF that matches what I saw on the screen.

[VAL.pdf](https://github.com/DeepBlueCLtd/RCO/files/13238797/VAL.pdf)


At the bottom of page 2, V/12/2022/34 is partially missing. At the bottom of page 3, V/12/2023/64 is completely missing.
