### ISSUE TITLE
Issues with Resource History Modal

### ISSUE THREAD

**Issue by TahaKhanAbdalli** [DeepBlueCLtd/RCO#917]
1. Navigate to the `user` listing page.
2. Open the `history modal` for a specific user.
3. Attempt to change the `page` of the listing on the history modal or apply a `filter`.
4. An error is encountered, and upon closing the modal, the entire page crashes.

### Suggestion

The issue arises when attempting to change the page `URL` within the modal, causing errors and subsequent crashes. To `address` this, it is recommended to create a dedicated page for viewing `user history`. By routing users to a separate page for history viewing, we can avoid the complications associated with modifying the `URL` within a modal. This approach ensures a smoother experience without impacting the current functionality of filters or pagination.

**Comment by IanMayo** [comment]
Yes @TahaKhanAbdalli - let's do this.
