### ISSUE TITLE
Link not provided in `Audit` for `Edit` of item

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#925]
A user has edited the remarks on an item.

The `EDIT` is shown in the audit log - but there isn't a clickable link to the item in the `name` column.

Note: double-check this.  There is not a `subject` for `edit` transactions, since we just know about the record being edited.  Check that @IanMayo wasn't confused about empty `subject` field.

**Comment by TahaKhanAbdalli** [comment]
I see that this `link` in `name` column is `clickable` after I edited an item

![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/d3934453-3913-45ff-b4ab-7170d007ea50)

**Comment by IanMayo** [comment]
Yes - I was just about to post a similar screenshot.  I know it's missing in their data. Will have to investigate further.

**Comment by IanMayo** [comment]
This code has been refactored.  Believed to no longer be an issue.
