### ISSUE TITLE
Reinstate `Change Password` button

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#936]
We've lost the `Change Password` from the top-right context menu.

We should put it back.

**Comment by TahaKhanAbdalli** [comment]
Do you remember when we added this feature in the past? I am facing some difficulties in implementing it.

**Comment by IanMayo** [comment]
Hello, wasn't it on the top-right popup menu?

**Comment by TahaKhanAbdalli** [comment]
I think it was in the user show page.

**Comment by IanMayo** [comment]
Yes, that's to reset the password for another user. It's normal for a user to be able to trigger their own password reset.

Maybe I imagined the fact that it used to be in the top-right menu. But, that seems the logical place for it to go.

I won't be at my desk for another hour or so. I can do some checking when I get there.

**Comment by TahaKhanAbdalli** [comment]
So should I go with it being in the `user menu` ? or should I wait for you?

**Comment by TahaKhanAbdalli** [comment]
Okay.

**Comment by TahaKhanAbdalli** [comment]
Should I create a separate `extension` for changing password or should I use `dataProvider`?

**Comment by IanMayo** [comment]
Do you know what logic we use for the current `set-password` feature (the one where someone first logs in after having `Reset password` done)?

**Comment by TahaKhanAbdalli** [comment]
yes it's an `extension`

**Comment by IanMayo** [comment]
Let's re-use that then, please.

**Comment by TahaKhanAbdalli** [comment]
It can't be reused, because for `change-password` additional logic for checking `current-password `is required. So I was thinking of creating a new `extension `also keeping in mind the `duplication`

**Comment by IanMayo** [comment]
Aah, of course.   A `change password` dialog needs the `current password` to be entered too, right?

**Comment by TahaKhanAbdalli** [comment]
Yes.
