### ISSUE TITLE
SQLite confusion

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#937]
There appears to be an issue in our login/auth processing.

The `user` data accessed by the `_extension` seems out of date.  I user had exceeded the number of login failures, and was locked out `lockoutAttempts=5`.

I cleared that using `Reset Password`.  I used the REST API to verify the lockout attempts was cleared.

When I tried to log in again, I was still locked out (password attempts).

I used sqlite-cli to view the data, and it still said `lockoutAttempts:5`.  But when I exited SQLite3 and re-entered, it had an updated value of zero.

I think we can (kind of) reproduce the issue using these steps:
1. install sqlite3. (`brew install sqlite3`)
2. navigate to db folder
3. open database `sqlite3 RCO2.sqlite`
4. view user 10 `select * from user where id=10;`
5. verify name is `Henrietta`
6. exit sqlite3 (`.quit`)
7. rename user to `Henrietta B` in VAL
8. view her data again via command line - see name is still `Henrietta`
9. exit sqlite (`.quit`)
10. view SQLite3 again - should see her name has updated.

It seems that _something-like_ this is happening: 
1. when sqlite3 opens, it doesn't handle `.WAL` changes 
2. when slqite3 closes, it updates to process WAL changes
3. when sqlite3 re-opens it contains updated data

I'm grateful for any help you can offer in moving this forward...

Doing some googling. _Maybe_ we're using multiple SQLite drivers:
https://stackoverflow.com/questions/68572090/why-data-is-lost-in-sqlite-database-with-wal-mode-on-when-connection-is-not-clos

I have checked our package.json and that for `soul`.  We're on two different versions of `Better-SQLite`. It may be worth pushing VAL back to the same as `Soul`.

**Comment by TahaKhanAbdalli** [comment]
The `sqlite` operations happen after the `toast` showing that the user has updated disappears which is around `5-10 seconds `after the operation. 
It wasn't showing the updates `username` but as soon as `toast` disappeared the data got updated. I have noticed it too that `react-admin` makes the api call after the toast goes away.

**Comment by IanMayo** [comment]
Yes. If I leave a sufficient pause, the backend does get updated.

But on the client network the user still had 5 logout attempts some minutes after it was reset.

Just to try to discount other possible causes, would you mind putting RCO/VAL onto the same vesrion of `Better-SQLite` as `Soul`?  I'll then re-test on target network.

**Comment by IanMayo** [comment]
I've just re-tested the above. It is certainly caused by the delay that `react-admin` introduces in order to allow an `Undo` behaviour.

This is not related to #934
