### ISSUE TITLE
`Save` not working for DestructionEdit

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#960]
In the DestructionEdit form, clicking `Save` does a screen refresh.  It doesn't actually save.

Plus, `Save` should only be enabled once the form is `dirty`.

**Comment by TahaKhanAbdalli** [comment]
Hi @IanMayo,
This issue is due to year field. At the front end we can see that there is a field of year while editing or creating the destruction, but in the database there is not any column with that name.
So, if I remove this field, then the save button works fine.
What's your opinion on this?

**Comment by IanMayo** [comment]
I can't quite remember why year is in there. But. yes - let's remove the `Year`.

**Comment by TahaKhanAbdalli** [comment]
Sure.

**Comment by IanMayo** [comment]
Hey @TahaKhanAbdalli  - did I say how much I disliked it when calls to the backend silently fail?   🤣 

This is a justification for that position.
