### ISSUE TITLE
Can't create new MediaType

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#966]
I can create a new media type on Heroku

But I can't on the target network.  

I am diagnosing what is happening via the `Network` tab.

RCO does a `POST` with the new media type.  The payload includes a new `id`.  On the target network, this is id `938`.  Note: `938` is already in use, and the media-types actually go up to `1061`.  I've tried it several times, and it is always `938`.

The `post` fails, with an error `UNIQUE constraint failed: mediaType.id`.

When I monitor what happens on Heroku, it appears to provide a valid id (an incremented version of the current max id)

I've inspected the schema of the SQLite database on the target network.  The `id` for `mediaType` is defined as `INTEGER NON NULL UNIQUE`.  I've just inspected the SQLite database for our mock data.  I see that it has the same `UNIQUE` property - so that's not the issue.

Note: the [schema definition](https://github.com/DeepBlueCLtd/RCO/blob/main/db/Scripts/full.sql#L87) says it should not be unique, but that doesn't match the actual database.

**Note:** this is another instance of RCO silently failing.  Aah, but we can't test it on Heroku or our dev machines.

**Comment by TahaKhanAbdalli** [comment]
The soul is using this function to return the total count of the rows in the table: 

<img width="338" alt="Screenshot 2023-12-29 at 1 06 51 PM" src="https://github.com/DeepBlueCLtd/RCO/assets/50602678/f2600bb7-c55b-47ab-bddb-420f9db3b6bb">


and we are using it to generate id:

<img width="629" alt="Screenshot 2023-12-29 at 1 07 35 PM" src="https://github.com/DeepBlueCLtd/RCO/assets/50602678/1f111ed3-be50-49d8-a654-1b60f0317671">

This on our end seems to be correct. However, if I can replicate it that would give more reference to the problem.
