### ISSUE TITLE
Button to reset displayed columns

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#991]
Users can choose which columns to display in most lists, they do this to tailor the content to the job in hand.

It is correct that RCO remembers which columns the user wants to view.

But, we should introduce a button (somewhere) to reset the currently displayed columns to the original default ones.

**Comment by TahaKhanAbdalli** [comment]
Hello @IanMayo,
Could you please confirm that it is okay? Reset Columns button position in the user menu?
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/8942016d-a557-4bd2-b8da-f27963964e1c)

**Comment by IanMayo** [comment]
Hello @TahaKhanAbdalli - is it possible to have the button the data grid header, so just that grid gets reset?

(but I can also see value in a reset all settings button in the user menu - I think users have experienced glitch where previous filter is still being applied, even though it's not currently in use.

**Comment by TahaKhanAbdalli** [comment]
Okay, let me check.

**Comment by TahaKhanAbdalli** [comment]
> Hello @TahaKhanAbdalli - is it possible to have the button the data grid header, so just that grid gets reset?
> 
> (but I can also see value in a reset all settings button in the user menu - I think users have experienced glitch where previous filter is still being applied, even though it's not currently in use.


To reset the columns in all lists, I used a handy tool called `useResetStore()` from React Admin. It quickly sets everything back to the default.
And for resetting all the filters, first, we clear the `LocalStorage`  which is efficiently handled by the React Admin hook `useResetStore()` . After that, we just need to redirect to the welcome page. 
The reasons for redirecting is that the filters grab their values from the URL. If we stick around on the same list, the filters won't disappear.
I just need a go head to implement this.

**Comment by IanMayo** [comment]
Sure, ok.  Two buttons: `Restore all default columns` and `Clear all filters`.

**Comment by TahaKhanAbdalli** [comment]
Okay.

**Comment by TahaKhanAbdalli** [comment]
One more thing. Both the buttons will be shown on the grid header. Right?
