### ISSUE TITLE
In `Create Batch` platform drop-down should be ordered by platform name

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#998]
When creating a batch, the platforms in the drop-down should be listed alphabetically, even once the user has started to enter a search term.

**Comment by TahaKhanAbdalli** [comment]
Could you please confirm this sorting in dropdown is okay in the attached file?
![image](https://github.com/DeepBlueCLtd/RCO/assets/50602678/67c3ae53-7c9d-4bb5-8e51-213baa8fe9b5)
